- name: enable mkhomedir
  tags:
    - ubuntu
    - mkhomedir
  become: true
  lineinfile:
    dest=/etc/pam.d/common-session
    line='session     required      pam_mkhomedir.so skel=/etc/skel umask=0022'

- name: enable sssd sudo functionality
  tags:
    - ubuntu
    - sssd
  become: true
  notify: 
    - restart sssd
    - restart ssh
  lineinfile:
    dest=/etc/sssd/sssd.conf
    regexp='^services.*'
    line='services = nss, pam, ssh, sudo'
