---
# handlers file for ansible-freeipa-client
#
- name: restart sssd
  tags: sssd
  become: true
  service:
    name=sssd
    state=restarted

- name: restart ssh
  tags: sssd
  become: true
  service:
    name=ssh
    state=restarted
